### PR TITLE
Ports deprecated 'x as Y' syntax (circa crystal v0.19.0) to 'x.as(Y)'

### PR DESCRIPTION
**Pull request by TheLonelyGhost**
Addresses #6 with corrected syntax

### CODE REVIEW

**Comment by TheLonelyGhost** [comment]
This also requires an update to `shard.yml` to update `spec2` library to the latest on `waterlink/spec2.cr` master branch. I see 3 ways of fixing this:

1. I can pull the changes into my fork
2. we can wait until a new release for `spec2` is cut and switch back to the official copy
3. we can continue using the `greyblake/spec2.cr` fork of it, point it to a new branch, and update that branch with the latest from `waterlink/spec2.cr` master branch (as of commit `eef5144d86f3aadf95811ffc0450be389db36fed`)

**Comment by greyblake** [comment]
@TheLonelyGhost Thanks a lot for the migration!  It would be nice to open PR for original spec2.cr, so @waterlink can merge it:)

**Comment by greyblake** [comment]
@TheLonelyGhost The change is available in version 0.1.4

**Comment by TheLonelyGhost** [comment]
@greyblake Oddly enough, it's already on master for @waterlink's repo, but it is yet unreleased. Instead of pointing to master for the foreseeable future, I figured it'd be better to point to a fork with the HEAD at the exact commit we need.

Now that I've said all of this, I reviewed the shards spec and we have another option for long-term support:

- Specify the commit SHA for @waterlink's current HEAD revision on master as `commit` in the shard.yml file

Once the new version of spec2 is released, we can point to the specific version, of course. Until then these are all intended to be stopgap measures.

**Pull request merged**
